### ISSUE TITLE
Tab Stems and longer beams

### ISSUE THREAD

**Issue by beckersi** [MatthewDorner/abcjs-vexflow-renderer#12]
Hi Matthew,
is it possible to display Tab Note Stems wih your renderer?
![canvas](https://user-images.githubusercontent.com/83134398/116786716-7935f280-aaa0-11eb-8358-f098161b20d8.png)

Also I would like to know if there is an easy way to render beams of four notes like in the example here:
![canvas1](https://user-images.githubusercontent.com/83134398/116786802-fcefdf00-aaa0-11eb-95db-a669175467d4.png)

Thanks,
Simon

**Comment by MatthewDorner** [comment]
Tab stems are not currently supported, but would probably be easy to implement since VexFlow supports them. Is this for a use case where you want to only show tabs and not sheet music? Because currently, the option is only to show/hide tabs, though an option to show/hide regular stave could be added. I avoided cluttering the tabs with elements that are already displayed in the regular stave above it.

As for beams, it relies on VexFlow's `Beam.generateBeams` for non-compound time signatures. I wrote my own code to handle beaming for compound time signatures, but your example looks like non-compound time. If VexFlow's beaming code has an option for this, this library could be made to support it. Otherwise I guess we could stop using `Beam.generateBeams` and adapt `generateBeamsCompound` for non-compound time signatures, to handle all beaming inside this library.

**Comment by beckersi** [comment]
Thank you for your reply. The Tab stems are for a use case where both tabs and sheet music are shown. However, it would be nice to have the option to turn tab stems on and off if it doesn't lead to too much cluttering.

**Comment by MatthewDorner** [comment]
I'll take a shot at implementing these, it probably isn't difficult to modify my beaming code to work for all time signatures, and I'd rather have beams of four notes too, if possible.

**Comment by MatthewDorner** [comment]
OK, I changed the beaming in 4/4 time to beam groups of 4 eighth notes, but left it to VexFlow defaults for other time signatures. Were you seeing issues in any other time signatures? Then also added the `tabStemsVisibility` in `renderOptions`. You'll have to also adjust `lineHeight` to make space for the stems.

**Comment by MatthewDorner** [comment]
Fixed in https://github.com/MatthewDorner/abcjs-vexflow-renderer/commit/e616dd25da5f68e0b82181a4caff31cb7505f228
